# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 67d97fd1723d14fa6720457b77a2bb8ab2837277d599afc0b5ba7c3287de8d3c0e11e508a4469fafb0bdb843530f3a6d3a86099321ef4d00eb715f68517c562e

test:
  secret_key_base: 85942e21f65a1af83ee29bb9518f1c14d01ea0a320b7c551ac7bb1b90887398009e52d25a694b430cb3d2976aff9da9819f6a9a65fa906317887e91da7e97495

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
